server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fqz
    username: root
    password: abcd1234
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
    max-wait: 10000
    max-active: 30
    test-on-borrow: true
  dubbo:
    application:
      name: order-service
    registry:
      protocol: zookeeper # 重要
      address:  127.0.0.1:3181,127.0.0.1:3182,127.0.0.1:3183
    protocol:
      name: dubbo
      port: 20881
    scan: com.fqz.order.service

mybatis:
  mapper-locations: classpath:mybatis/mapping/*.xml
  type-aliases-package: com.fqz.order.entity

